In [ ]:
#2-1두 개의 정수를 입력받아서 다음과 같이 4가지 관계 연산자의 결과를 출력하시오. 이 때 입력받은 두 정수를 이용하여 출력하시오
#입력값 4 5 , 출력 4>5---0 , 4< 5---1, 4>=5---0 , 4<=5---1

a, b = map(int, input().split())
#if(a<b):
  #print(a,'>', b ,'---',0 ) #왼쪽 값이 오른쪽 값보다 크다
  #print(a,'<', b ,'---',1 ) #왼쪽 값이 오른쪽 값보다 작다
  #print(a,'>=',b ,'---',0 ) #왼쪽 값이 오른쪽 값보다 크거나 동일하다
  #print(a,'<=',b ,'---',1 ) #왼쪽 값이 오른쪽 값보다 작거나 동일하다

  print(a,'>', b ,'---',a > b ) #왼쪽 값이 오른쪽 값보다 크다
  print(a,'<', b ,'---',a < b ) #왼쪽 값이 오른쪽 값보다 작다
  print(a,'>=',b ,'---',a >= b ) #왼쪽 값이 오른쪽 값보다 크거나 동일하다
  print(a,'<=',b ,'---',a <=b) #왼쪽 값이 오른쪽 값보다 작거나 동일하다

In [ ]:
#2-2 3개의 정수를 입력받아 첫 번째 수가 가장 크면 1 아니면 0을 출력하고 세 개의 수가 모두 같으면 1아니면 0의 출력한다
#입력 예 10 9 9   // 출력  1 0
a, b, c = map(int, input().split())


if (a > b) and (a > c):
    d = 1
#elif (b >= a) and (b >= c):
    d=0
else:
    d=0
if(a==b) and (a==c):
  f=1
else:
  f=0
print(d, f)

In [ ]:
#2-3 두개의 정수를 입력받아 첫 번째 수는 후치 증가연산자를 사용하고 두 번째 수는 전치 감소 연산자를 사용하여 두 수의 곱을 구한 후 각각의 값을 출력하시오
#입력 10 20 , 출력 11 19 190??
a, b = map(int, input().split())

a+=1
b-=1
print(a, b, a*b)

In [ ]:
#2-4 민수와 기영이의 키와 몸무게를 입력받아 민수가 키도 크고 몸무게도 크면 1 그렇지 않으면 0을 출력하는 프로그램을 작성하시오
# 입력 150 35 , 145 35 출력 0
a, b = map(int, input().split())
c, d = map(int, input().split())

if(a> c) and (b> d):
  print(1)
else:
  print(0)