In [118]:
#1-1 합계와 평균 수식 내기 kor90, mat80, eng 100, sum 270, avg:
kor =int(input("kor 점수를 입력하시오:"))
mat =int(input("mat 점수를 입력하시오:"))
eng =int(input("eng 점수를 입력하시오:"))

sum = kor + mat + eng
avg = sum//3

print("kor", kor)
print("mat", mat)
print("eng", eng)
print("avg", avg)

kor 점수를 입력하시오:78
mat 점수를 입력하시오:35
eng 점수를 입력하시오:22
kor 78
mat 35
eng 22
avg 45

In [121]:
#1-2
#line = "T" *10
#print(line)
#print(line)

print('''\
TTTTTTTTTT
TTTTTTTTTT
    TT
    TT
    TT''')

TTTTTTTTTT
TTTTTTTTTT
    TT
    TT
    TT

In [122]:
#1-3 10 20 30 , 10+20=30
#a = int(input("변수 를 입력하시오:"))
#b = int(input("변수 를 입력하시오:"))
#c = int(input("변수 를 입력하시오:"))

a = 10
b = 20
c = 30
print(a ,'+', b ,'=', c)

10 + 20 = 30

In [123]:
#1-4 세개의 정수 20 50 100 을 입력받아 합과 평균을 출력하시오 평균은 소수 이하는 버리시오
a, b, c = map(int, input().split())

sum = a + b + c
avg = sum//3

print(sum, avg)

20 50 100
170 56

In [124]:
#1-5 야드를 입력받아 cm 로 출력 10.1 yard = 923.5 소수 둘째 자리에서 반올림하여 첫째짜리 까지 출력(1야드 91.44cm)


a = float(input("yard? "))

double = 91.44 * a
print(a ,"yard","=" , format(double, ".1f"), "cm")

yard? 10.1
10.1 yard = 923.5 cm

In [125]:
#2-1두 개의 정수를 입력받아서 다음과 같이 4가지 관계 연산자의 결과를 출력하시오. 이 때 입력받은 두 정수를 이용하여 출력하시오
#입력값 4 5 , 출력 4>5---0 , 4< 5---1, 4>=5---0 , 4<=5---1

a, b = map(int, input().split())
#if(a<b):
  #print(a,'>', b ,'---',0 ) #왼쪽 값이 오른쪽 값보다 크다
  #print(a,'<', b ,'---',1 ) #왼쪽 값이 오른쪽 값보다 작다
  #print(a,'>=',b ,'---',0 ) #왼쪽 값이 오른쪽 값보다 크거나 동일하다
  #print(a,'<=',b ,'---',1 ) #왼쪽 값이 오른쪽 값보다 작거나 동일하다

  print(a,'>', b ,'---',a > b ) #왼쪽 값이 오른쪽 값보다 크다
  print(a,'<', b ,'---',a < b ) #왼쪽 값이 오른쪽 값보다 작다
  print(a,'>=',b ,'---',a >= b ) #왼쪽 값이 오른쪽 값보다 크거나 동일하다
  print(a,'<=',b ,'---',a <=b) #왼쪽 값이 오른쪽 값보다 작거나 동일하다

IndentationError: ignored

In [127]:
#2-2 3개의 정수를 입력받아 첫 번째 수가 가장 크면 1 아니면 0을 출력하고 세 개의 수가 모두 같으면 1아니면 0의 출력한다
#입력 예 10 9 9   // 출력  1 0
a, b, c = map(int, input().split())


if (a > b) and (a > c):
    d = 1
#elif (b >= a) and (b >= c):
    d=0
else:
    d=0
if(a==b) and (a==c):
  f=1
else:
  f=0
print(d, f)

10 9 9
0 0

In [128]:
#2-3 두개의 정수를 입력받아 첫 번째 수는 후치 증가연산자를 사용하고 두 번째 수는 전치 감소 연산자를 사용하여 두 수의 곱을 구한 후 각각의 값을 출력하시오
#입력 10 20 , 출력 11 19 190??
a, b = map(int, input().split())

a+=1
b-=1
print(a, b, a*b)

10 20
11 19 209

In [129]:
#2-4 민수와 기영이의 키와 몸무게를 입력받아 민수가 키도 크고 몸무게도 크면 1 그렇지 않으면 0을 출력하는 프로그램을 작성하시오
# 입력 150 35 , 145 35 출력 0
a, b = map(int, input().split())
c, d = map(int, input().split())

if(a> c) and (b> d):
  print(1)
else:
  print(0)

150 35
145 35
0

In [136]:
#3-1 정수를 입력받아 0이면 zero, 양수면 plus , 음수면 minus
a = int(input(""))

if a == 0:
  print("zero")

elif (a>0):
  print("plus")

else:
  a<0
  print("minus")

0
zero

In [137]:
#3-2 영문 대문자를 입력받아 A,B,C,D,F 이면 출력 그 외 문자이면 error 라고 출력
text = input("")
text1 = (text.upper()) #대문자로 변환
if (text1 == 'A'):
  print("Excellent")
elif (text1 == 'B'): 
  print("Good")
elif (text1 == 'C'):
  print("Usually")
elif (text1 == 'D'):
  print("Effort")
elif (text1 == 'F'): 
  print("Failure")
else: 
  print("error")

b
Good

In [138]:
#3-3 1번은 개 , 2번은 고양이, 3번은 병아리로 정하고 번호를 입력하면 동물을 영어로 출력하는 프로그램

num = int(input("Number?"))

if (num==1):
  print("dog")

elif (num==2):
  print("cat")

elif (num==3):
  print("chick")

else:
  print("I don\'t know.")

Number?2
cat

In [139]:
#3-4 정수 1~12 사이 에서 입력받아 평년의 경우 해당 월 수를 출력
month = int(input("월을 입력하시오:"))
list = [ 1, 3, 5, 7, 8, 10, 12]
list1 = [4, 6, 9, 11]
list2 = [2]
if month in list :
  print(31,"일")

elif month in list1 :
  print(30,"일")
elif month in list2 :
  print(28,"일")
else:
  print("잘못 입력했습니다.")

월을 입력하시오:2
28 일

In [134]:
#3-5 남자는 M, 여자는 F 로 나타내고 18세 이상을 성인으로 하자 
#성별을 입력받아 MAN , WOMAN , BOY, GIRL, 로 구분 예 F 15 = GIRL

gender = input("성별을 입력하시오:")
age    = int(input("나이를 입력하시오:"))


if (gender == 'M') and (age>= 18):
  print("MAN")
elif (gender == 'M') and (age > 18):
  print("BOY")
elif (gender == 'F') and (age >= 18):
  print("WOMAN")
else:
  print("GIRL")

성별을 입력하시오:F
나이를 입력하시오:15
GIRL

In [140]:
#3-6 년도를 입력받아 윤년(leap year) 인지 평년(common year)인지 판단하는 프로그램 작성
# 2008 , leap year
#400으로 나누어 떨어지면 윤년 또는 4로 나누어 떨어지고 100으로 나누어 떨어지지 않으면 윤년이다. 나머지는 평년이다


year = int(input(''))
if (((year%4 == 0) and (year% 100 !=0)) or year % 400 == 0):
  print("leap year")

else:
  print("common year")

2008
leap year

In [17]:
#4-1  100이하의 양의 정수만 입력된다.
# while 문의 이용하여 1부터 입력받은 정수까지의 합을 구하여 출력하는 프로그램을 작성하시오 ex) 입력 10 / 출력 55

x = int(input())
sum = 0
number = 1
while number <= x:
  sum += number
  number += 1
 
print(sum)

10
55

In [16]:
#4-2 100이하의 정수를 입력받아서 입력받은 정수부터 100까지의 합을 출력하는 프로그램을 작성하시오.
# ex) 입력 95 / 출력 585

num = int(input())
sum = 0

while num <= 100:
  sum = sum + num
  num = num+1

print(sum)

95
585

In [51]:
#4-3 한 개의 자연수를 입력받아  그 수의 배수를 차례로 10개 출력하는 프로그램을 작성하시오.
# ex) 입력 5 / 출력 5 10 15 20 25 30 40 45 50
num = int(input())
num_list=[]

for i in range(10):
  i= i + 1
  y = num * i
  num_list.append(y)

num_list

5

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [52]:
#4-5 0이 입력될 때 까지 정수를 계속 입력받아 3의 배수와 5을 배수를 제외한 수들의 개수를 출력하는 프로그램을 작성하시오.
# ex) 입력 1 2 3 4 5 6 7 8 9 10 0 / 5

#num_list = []

#while True:
 #num = int(input())
 #if num >=0:
  #if num % 3 != 0 and num % 5 !=0:
   # num_list.append(num)
    
  #else:
   # break;
#print(num_list)

sum = 0
while True:
  num = int(input())
  if num == 0:
    break
  else:
    if num%3 !=0 and num%5 !=0:
      sum = sum +1

print(sum)

1
2
3
4
5
6
7
8
9
10
0
5

In [18]:
#4-6 삼각형의 밑변의 길이를 높이를 입력받아 넓이를 출력하고, "continue? " 에서 하나의 문자를 입력받아 그 문자가 'Y' 나 'y' 이면 작업을 반복하고 
#다른 문자이면 종료하는 프로그램(넓이는 반올림하여 소수 첫째 자리까지)


while True:
  base = int(input('Base: '))
  height = int(input('Height: '))
  area = base * height / 2
  print('Triangle width = ', area)
  text = input("continue?")
  ans = (text.upper())
  
  if(ans == 'Y'):
    print()
  else:
    break

Base: 10
Height: 5
Triangle width =  25.0
continue?y

Base: 11
Height: 25
Triangle width =  137.5
continue?n

In [19]:
#4-7 아래와 같이 출력되는 프로그램을 작성하시오.
#출력 2 3 4 5 6 /  3 4 5 6 7 / 4 5 6 7 8 / 5 6 7 8 9 / 6 7 8 9 10

for y in range(5):
  for x in range(5):
    x+=2
  
    print(x+y , end=" ")

    
  print("")

2 3 4 5 6
3 4 5 6 7
4 5 6 7 8
5 6 7 8 9
6 7 8 9 10

In [20]:
#5-1 자연수 n 을 입력받고 1부터 홀수를 차례대로 더해나가면서 합이 n 이상이면 그 때까지 더해진 홀수의 개수와 그 수의 합을 출력하는 프로그램 작성
# 입력 100/ 출력 10 100 

num= int(input())
x = 1
sum = 0
y = 0  # 홀수 개수

while sum < num:
    if x % 2 != 0:
        sum = sum + x
        y = y+1

    else:
        pass
    x = x+1

print(y ,sum)

100
10 100

In [39]:
#5-2 2부터 9까지의 수 중 2개를 입력받아 입력받은 수 사이의 구구단을 출력하는 프로그램을 작성하시오. 단 반드시 먼저 입력된 수의 구구단 부터 아래의
# 형식에 맞게 출력해야함 구구단 사이의 공백은 3칸   입력 5 3 / 출력 5단 4단 3단

a, b = map(int, input(). split())

if ((a < 2) or (a > 9)) or ((b < 2) or (b > 9)):
  print()  
elif (a>b):
  for i in range(1, 10):
    for j in range(a, b-1 , -1): 
      print(j , '*' , i , '=' , i*j ,end="  ")
    print()
else : 
  for i in range(1, 10):
    for j in range(a, b+1 , 1): 
      print(i , '*' , j , '=' , i*j , end="  ")      
    print()

5 3
5 * 1 = 5  4 * 1 = 4  3 * 1 = 3
5 * 2 = 10  4 * 2 = 8  3 * 2 = 6
5 * 3 = 15  4 * 3 = 12  3 * 3 = 9
5 * 4 = 20  4 * 4 = 16  3 * 4 = 12
5 * 5 = 25  4 * 5 = 20  3 * 5 = 15
5 * 6 = 30  4 * 6 = 24  3 * 6 = 18
5 * 7 = 35  4 * 7 = 28  3 * 7 = 21
5 * 8 = 40  4 * 8 = 32  3 * 8 = 24
5 * 9 = 45  4 * 9 = 36  3 * 9 = 27

In [54]:
#5-3 행과 열의 수를 입력받아 다음과 같이 출력하시오 입력 3 4 / 출력 예 1 2 3 4  ,  2 4 6 8 , 3 6 9 12

a, b = map(int, input(). split())

for i in range(1, a+1):
  for j in range(1, b+1):
    print(i*j, end=" ")
  print()

3 4
1 2 3 4
2 4 6 8
3 6 9 12

In [56]:
#5-4 자연수 n을 입력받아 n줄 만큼 다음과 같이 출력하는 프로그램 작성   입력 5 / 출력 * ** *** **** *****
n = int(input())

for i in range(1,n+1): #행
  for j in range(1, i+1): #열
    print("*", end="")
  print()

5
*
**
***
****
*****

In [62]:
#5-5 자연수 n을 입력받아서 다음과 같이 출력하시오   입력 3  / 출력 ***** *** *

n = int(input())

for i in range(n):
    for j in range(n,i,-1):
        print(' ',end='')

    for j in range((i+1)*2-1):
        print("*",end='')
    print()

3
   *
  ***
 *****

In [110]:
#5-6 1부터 100까지의 정수 중  한개를 입력받아 100 보다 작은 배수들을 차례로 출력하다가 10의 배수가 출력되면 프로그램을 종료하도록 작성
# 입력 7  / 출력 7 14 21 28 35 42 49 56 63 70

num = int(input())
num_list=[]
i=0

while num >0 and num <101:
  i= i+1
  y = num * i
  num_list.append(y)
  if y % 10 == 0:
    break

num_list

7

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70]

In [117]:
#5-7 자연수 n을 입력받아 "출력 예" 와 같이 공백으로 구분하여 출력하는 프로그램을 작성      
#주의!! 숫자를 공백으로 구분하되 줄사이에 빈줄을 없다.


# 미완성 !!!!!!!!!!!!!
n = int(input())

for j in range(n+1):
  for i in range(1,n+1):
    if i <= j:
     print(i, end=" ")
    else:
      print(' ',end=' ')
  print()



#n = int(input())
#for i in range(1,n+1):
   # print(' '*(n-i), end='')
    #print('*'*i)

3

1
1 2
1 2 3

In [65]:
#5-8 자연수 n을 입력받아 "출력 예" 와 같이 공백으로 구분하여 출력하는 프로그램을 작성
#주의!! 숫자를 공백으로 구분하되 줄사이에 빈줄을 없다

n = int(input())

number = 1

for i in range(n):
  for j in range(n):
    if i <= j:
      print(number, end=" ")
      number += 1
    else:
      print(' ',end=' ')
  print()

3
1 2 3
  4 5
    6

In [72]:
#5-9 자연수 n을 입력받아 "출력 예"와 같이 n x n 크기에 공백으로 구분하여 출력 작성
# 10 미만의 홀수만 출력하시오 주의!! 숫자는 공백으로 구분하되 줄 사이에 빈줄은 없다.

n = int(input())

num = 1

for i in range(n):
  for j in range(n):
    print(num, end=' ')
    num += 2
    if num > 10:
      num = 1
  print()

3
1 3 5
7 9 1
3 5 7